### ISSUE TITLE
Pass platform-dependent arguments to writer

### ISSUE THREAD

**Issue by gerritholl** [pytroll/trollflow2#107]
## Feature Request

**Is your feature request related to a problem? Please describe.**

NinJoTIFF needs the satellite ID in the header.  The NinJoTIFF writer needs the satellite ID as a keyword argument.  The trollflow2 `save_datasets` plugin needs to pass the satellite ID to the NinJoTIFF writer.  The user needs to write this satellite ID in the trollflow2 configuration file.  This is difficult if a single trollflow2 instance is used to process multiple satellites.

**Describe the solution you'd like**

I would like that in `trollflow2.yaml`, there is a way for the value of at arbitrary keyword argument passed to a plugin to change depending on the satellite platform.  Specifically, I need the value of `sat_id` passed to the writer `ninjotiff_nostretch` to depend on the `platform_name`.

Some ways I can think of how this might be implemented.

Passing a callable:

```yaml
product_list:
  ...
  areas:
    nqceur1km:
      areaname: nqceur1km
      products:
        '1':
          ...
          formats:
            - &ninjotiff
              format: tif
              writer: ninjotiff_nostretch
              sat_id: !!python/name:trollflow2.plugins.get_sat_id
              chan_id: ...
```

trollflow2 would replace the value of `sat_id` by the result of the callable, which it calls using the same arguments it would call the writer.

Configuring a translation table with a magic keyword:

```yaml
product_list:
  ...
  keyword_translator:
    sat_id:
      platform_id:
        Metop-A: 7800014
        Metop-B: 7800015
      ...
  min_coverage: 15.0
  areas:
    nqceur1km:
      areaname: nqceur1km
      products: &chans_and_overview
        '1':
          ...
          formats:
            - &ninjotiff
              format: tif
              writer: ninjotiff_nostretch
              sat_id: !!python/name:trollflow2.sentinel
              chan_id: ...
```

when encountering the sentinel, trollflow2 translates the sat_id keyword.

Some other way:

There may be other ways I'm not thinking of.

**Describe any changes to existing user workflow**

This should be backward compatible.

**Additional context**

Other solutions, without changing anything in trollflow2:

- Adapt pyninjotiff and do the translation there.  This would require pyninjotiff to know, based on the platform name which is available from the scene metadata, what ID should be written.  This adds a complication to pyninjotiff.
- Adapt NinJo, so it doesn't need those IDs.  In principle, all information NinJo should need is available from either the filename or the header.  Although there is work going on for NinJo to understand GeoTIFF, it will be awhile until all our users use a version that can.  We cannot wait for this.
- Implement an additional processing step that adds the IDs.  This is complicated, because by then the files would have been already written.
- Use different trollflow2 instances for different satellites, with different configuration files.  This would involve nearly identical configuration files.  [YAML does not natively support includes](https://stackoverflow.com/a/15437697/974555), so this would become a maintenance burden with nearly identical files spread around.  In our case, we process the five currently operational satellites carrying AVHRR.  This burden could be reduced if trollflow2 implemented its own include directive.
