### ISSUE TITLE
Add support for dask.distributed

### ISSUE THREAD

**Issue by pnuu** [pytroll/trollflow2#82]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Trollflow2 should eventually support `dask.distributed` for parallellism. Both local cluster and external cluster should be supported, but also the current default scheduler should be a possibility.

**Describe the solution you'd like**
When suitable configuration is given, use `dask.distributed.Client()` to either connect to a external scheduler, or create a local cluster of workers. If `client` config isn't given, the current behaviour of default scheduler should be used.

The configuration could be something like this:

```yaml
client:
  # If scheduler address is given, use that to access the workers
  scheduler_address: <ip>:8786
  # Otherwise, or if the scheduler can't be connected, local cluster is used with the following params.
  # For the missing arguments the defaults will be used.
  local_cluster:
    nprocs: 4
    nthreads: 1
```

**Describe any changes to existing user workflow**
Ideally this shouldn't affect the default usage.

**Additional context**
Some things that might affect the implementation and/or use:

- the client will be recreated for every scene when the new process is started
- only some readers/resamplers/writers can be used with `dask.distributed`
